language: node_js
node_js:
  - "8.10"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn
cache:
  yarn: true
  directories:
    - ".eslintcache"
    - "node_modules"
script:
  - yarn run coverage
  - echo service_name: travis-ci >> .coveralls.yml
  - echo repo_token: {$COVERALLS_TOKEN} >> .coveralls.yml
  - yarn run coveralls
after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverage/coverage-final.json
branches:
  only:
    - master
    - develop

