language: node_js
node_js:
  - "8.10"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn
cache:
  yarn: true
  directories:
    - ".eslintcache"
    - "node_modules"
script:
  - yarn run test
branches:
  only:
    - master
    - develop

